language: android
sudo: false
jdk:
  - oraclejdk7
android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-android-support
env:
  - ANDROID_HOME=/usr/local/android-sdk
before_script:
    - . $HOME/.nvm/nvm.sh
    - nvm install 6
    - nvm use 6
    - npm install
script: "make travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
